//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace maerskline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Shippment
    {
        public int shippmentID { get; set; }
        
        public Nullable<int> source { get; set; }
        
        public Nullable<int> destination { get; set; }
        [Required]
        public Nullable<System.DateTime> departTime { get; set; }
        [Required]
        public Nullable<System.DateTime> arrivalTime { get; set; }
        public Nullable<int> cargoID { get; set; }
    
        public virtual Cargo Cargo { get; set; }
        public virtual Warehouse Warehouse { get; set; }
        public virtual Warehouse Warehouse1 { get; set; }
    }
}
